### PR TITLE
Typos in readme

### PR DESCRIPTION
**Pull request by monkstone**
@poqudrof this looks very interesting, recently I have been giving [JRubyArt web site](https://ruby-processing.github.io/JRubyArt/) some love. But I fully intend to get propane to a similar level, at the moment I'm doing some work to convert more [samples to propane](https://github.com/ruby-processing/propane-examples) which serve two purposes 
-  to make sure all types of sketch can be converted
-  to build out examples for instructional purposes

The atom editor is working very well for me and that is another distraction

Couple of typos but its far too soon to create pull request

### CODE REVIEW

**Comment by monkstone** [comment]
Seems to work pretty well, however not exactly user friendly. For [ruby-processing](https://github.com/jashkenas/ruby-processing/blob/master/lib/ruby-processing/exporters/application_exporter.rb) we did it pretty seamlessly from ruby, providing you get all your jars in right place (`Rakefile` and `wget`) classpath is easy so I'm not 100% sure what `rawr` really offers. PS: I extracted jar Manifest, we could do this with Rakefile and pom.rb see propane. We would choose to call it something other than `monkeybars`

``` bash
Manifest-Version: 1.0
Class-Path: lib/java/gluegen-rt-2.3.2-natives-linux-amd64.jar
  lib/java/gluegen-rt-2.3.2.jar
  lib/java/propane.jar
  lib/java/jogl-all-2.3.2-natives-linux-amd64.jar
  lib/java/gluegen-rt-2.3.2-natives-macosx-universal.jar
  lib/java/core-3.2.1.jar
  lib/java/jruby-complete.jar
  lib/java/jogl-all-2.3.2.jar
  lib/java/jogl-all-2.3.2-natives-macosx-universal.jar
  .
Main-Class: org.monkeybars.rawr.Main
```

This might be a simpler approach (and more up to date)
https://github.com/jruby/jruby/wiki/StandaloneJarsAndClasses

**Comment by monkstone** [comment]
I'd forgotten about this [old blogpost of mine](http://learning-ruby-processing.blogspot.co.uk/2015/07/experimenting-with-standalone-app-using.html) should be possible to hook up something this way.

**Comment by poqudrof** [comment]
This solution is for sure not the best but is has the benifit of working quite easily with minor configuration. 
Thank you for your fixing, I was quite in a hurry yesterday :)

**Comment by monkstone** [comment]
@poqudrof It would be nice to have a really simple solution (warbler might be the way) but unfortunately the developers try to cover every eventuality, and of course bend over backwards to accommodate rails projects (which is way too opinionated).  I have found polyglot maven pretty intuitive, and it can manage jar dependencies really well.  The one thing about warbler and JBundler is that the jruby guys support it.

**Pull request merged**
